// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddJavaToDownloadList(arg1) {
  return window['go']['main']['App']['AddJavaToDownloadList'](arg1);
}

export function AddLoaderToDownloadList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddLoaderToDownloadList'](arg1, arg2, arg3, arg4);
}

export function AddModToDownloadList(arg1, arg2) {
  return window['go']['main']['App']['AddModToDownloadList'](arg1, arg2);
}

export function AddModpackToDownloadList(arg1, arg2) {
  return window['go']['main']['App']['AddModpackToDownloadList'](arg1, arg2);
}

export function AddToDownloadList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddToDownloadList'](arg1, arg2, arg3, arg4);
}

export function AddToDownloadListWithLoader(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddToDownloadListWithLoader'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CancelDownloadList() {
  return window['go']['main']['App']['CancelDownloadList']();
}

export function CheckFirstRun() {
  return window['go']['main']['App']['CheckFirstRun']();
}

export function CheckLoaderInstalled(arg1, arg2) {
  return window['go']['main']['App']['CheckLoaderInstalled'](arg1, arg2);
}

export function CreateExternalUser(arg1, arg2) {
  return window['go']['main']['App']['CreateExternalUser'](arg1, arg2);
}

export function CreateGuestUser(arg1, arg2) {
  return window['go']['main']['App']['CreateGuestUser'](arg1, arg2);
}

export function CreateOfflineUser(arg1, arg2) {
  return window['go']['main']['App']['CreateOfflineUser'](arg1, arg2);
}

export function CreatePremiumUser(arg1, arg2) {
  return window['go']['main']['App']['CreatePremiumUser'](arg1, arg2);
}

export function CreateServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function DeleteMod(arg1) {
  return window['go']['main']['App']['DeleteMod'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DownloadAuthlibInjector() {
  return window['go']['main']['App']['DownloadAuthlibInjector']();
}

export function DownloadVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadVersion'](arg1, arg2, arg3);
}

export function GenerateConnectionCode(arg1) {
  return window['go']['main']['App']['GenerateConnectionCode'](arg1);
}

export function GetAppDir() {
  return window['go']['main']['App']['GetAppDir']();
}

export function GetAuthlibInjectorPath() {
  return window['go']['main']['App']['GetAuthlibInjectorPath']();
}

export function GetBackgroundImage() {
  return window['go']['main']['App']['GetBackgroundImage']();
}

export function GetBackgroundImageDataURL() {
  return window['go']['main']['App']['GetBackgroundImageDataURL']();
}

export function GetBingDailyImage() {
  return window['go']['main']['App']['GetBingDailyImage']();
}

export function GetCachedBingImage() {
  return window['go']['main']['App']['GetCachedBingImage']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDefaultModDir(arg1) {
  return window['go']['main']['App']['GetDefaultModDir'](arg1);
}

export function GetDownloadList() {
  return window['go']['main']['App']['GetDownloadList']();
}

export function GetDownloadListCount() {
  return window['go']['main']['App']['GetDownloadListCount']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetExternalAuthData(arg1) {
  return window['go']['main']['App']['GetExternalAuthData'](arg1);
}

export function GetFabricVersions(arg1) {
  return window['go']['main']['App']['GetFabricVersions'](arg1);
}

export function GetForgeVersions(arg1) {
  return window['go']['main']['App']['GetForgeVersions'](arg1);
}

export function GetGlobalConfig() {
  return window['go']['main']['App']['GetGlobalConfig']();
}

export function GetInstalledVersions() {
  return window['go']['main']['App']['GetInstalledVersions']();
}

export function GetJavaDownloadList() {
  return window['go']['main']['App']['GetJavaDownloadList']();
}

export function GetJavaInfo(arg1) {
  return window['go']['main']['App']['GetJavaInfo'](arg1);
}

export function GetJavaRequirement(arg1) {
  return window['go']['main']['App']['GetJavaRequirement'](arg1);
}

export function GetLaunchCommand(arg1) {
  return window['go']['main']['App']['GetLaunchCommand'](arg1);
}

export function GetMSAuthData(arg1) {
  return window['go']['main']['App']['GetMSAuthData'](arg1);
}

export function GetMinecraftDir() {
  return window['go']['main']['App']['GetMinecraftDir']();
}

export function GetModDependencies(arg1) {
  return window['go']['main']['App']['GetModDependencies'](arg1);
}

export function GetModDetail(arg1) {
  return window['go']['main']['App']['GetModDetail'](arg1);
}

export function GetModList(arg1) {
  return window['go']['main']['App']['GetModList'](arg1);
}

export function GetModTranslationFileContent() {
  return window['go']['main']['App']['GetModTranslationFileContent']();
}

export function GetModVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetModVersions'](arg1, arg2, arg3);
}

export function GetModpackVersions(arg1) {
  return window['go']['main']['App']['GetModpackVersions'](arg1);
}

export function GetModrinthCategories() {
  return window['go']['main']['App']['GetModrinthCategories']();
}

export function GetNeoForgeVersions(arg1) {
  return window['go']['main']['App']['GetNeoForgeVersions'](arg1);
}

export function GetOptiFineVersions(arg1) {
  return window['go']['main']['App']['GetOptiFineVersions'](arg1);
}

export function GetPortableJavaInfo() {
  return window['go']['main']['App']['GetPortableJavaInfo']();
}

export function GetPortableJavaPath() {
  return window['go']['main']['App']['GetPortableJavaPath']();
}

export function GetQGLDir() {
  return window['go']['main']['App']['GetQGLDir']();
}

export function GetRecommendedJavaForVersion(arg1) {
  return window['go']['main']['App']['GetRecommendedJavaForVersion'](arg1);
}

export function GetSelectedVersion() {
  return window['go']['main']['App']['GetSelectedVersion']();
}

export function GetServerDir() {
  return window['go']['main']['App']['GetServerDir']();
}

export function GetServerList() {
  return window['go']['main']['App']['GetServerList']();
}

export function GetServerLogs() {
  return window['go']['main']['App']['GetServerLogs']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetShowExportLaunchCommand() {
  return window['go']['main']['App']['GetShowExportLaunchCommand']();
}

export function GetThemeColor() {
  return window['go']['main']['App']['GetThemeColor']();
}

export function GetTranslationCount() {
  return window['go']['main']['App']['GetTranslationCount']();
}

export function GetUserConfig(arg1) {
  return window['go']['main']['App']['GetUserConfig'](arg1);
}

export function GetUserType(arg1) {
  return window['go']['main']['App']['GetUserType'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetUsersDir() {
  return window['go']['main']['App']['GetUsersDir']();
}

export function GetVersionManifest() {
  return window['go']['main']['App']['GetVersionManifest']();
}

export function GetYggdrasilServerInfo(arg1) {
  return window['go']['main']['App']['GetYggdrasilServerInfo'](arg1);
}

export function ImportMod(arg1) {
  return window['go']['main']['App']['ImportMod'](arg1);
}

export function InstallFabric(arg1, arg2) {
  return window['go']['main']['App']['InstallFabric'](arg1, arg2);
}

export function InstallForge(arg1, arg2) {
  return window['go']['main']['App']['InstallForge'](arg1, arg2);
}

export function InstallNeoForge(arg1, arg2) {
  return window['go']['main']['App']['InstallNeoForge'](arg1, arg2);
}

export function InstallOptiFine(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallOptiFine'](arg1, arg2, arg3);
}

export function IsGuestLocked() {
  return window['go']['main']['App']['IsGuestLocked']();
}

export function IsPortableMode() {
  return window['go']['main']['App']['IsPortableMode']();
}

export function IsVersionIsolation() {
  return window['go']['main']['App']['IsVersionIsolation']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function LockGuest() {
  return window['go']['main']['App']['LockGuest']();
}

export function LoginUser(arg1, arg2) {
  return window['go']['main']['App']['LoginUser'](arg1, arg2);
}

export function LoginYggdrasil(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginYggdrasil'](arg1, arg2, arg3);
}

export function ParseConnectionCode(arg1) {
  return window['go']['main']['App']['ParseConnectionCode'](arg1);
}

export function ReadLicenseFile() {
  return window['go']['main']['App']['ReadLicenseFile']();
}

export function RefreshExternalToken(arg1) {
  return window['go']['main']['App']['RefreshExternalToken'](arg1);
}

export function RefreshMicrosoftToken(arg1) {
  return window['go']['main']['App']['RefreshMicrosoftToken'](arg1);
}

export function RemoveFromDownloadList(arg1) {
  return window['go']['main']['App']['RemoveFromDownloadList'](arg1);
}

export function ResolveModDependencies(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveModDependencies'](arg1, arg2, arg3);
}

export function SaveExternalAuthData(arg1, arg2) {
  return window['go']['main']['App']['SaveExternalAuthData'](arg1, arg2);
}

export function SaveGlobalConfig(arg1) {
  return window['go']['main']['App']['SaveGlobalConfig'](arg1);
}

export function SaveMSAuthData(arg1, arg2) {
  return window['go']['main']['App']['SaveMSAuthData'](arg1, arg2);
}

export function SaveUserConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveUserConfig'](arg1, arg2);
}

export function ScanVersions() {
  return window['go']['main']['App']['ScanVersions']();
}

export function SearchJava() {
  return window['go']['main']['App']['SearchJava']();
}

export function SearchModpacks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchModpacks'](arg1, arg2, arg3, arg4);
}

export function SearchMods(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchMods'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchModsByChineseName(arg1) {
  return window['go']['main']['App']['SearchModsByChineseName'](arg1);
}

export function SelectBackgroundImage() {
  return window['go']['main']['App']['SelectBackgroundImage']();
}

export function SelectJavaForVersion(arg1) {
  return window['go']['main']['App']['SelectJavaForVersion'](arg1);
}

export function SelectModSaveDir() {
  return window['go']['main']['App']['SelectModSaveDir']();
}

export function SendServerCommand(arg1) {
  return window['go']['main']['App']['SendServerCommand'](arg1);
}

export function SetBackgroundImage(arg1) {
  return window['go']['main']['App']['SetBackgroundImage'](arg1);
}

export function SetCurrentUser(arg1) {
  return window['go']['main']['App']['SetCurrentUser'](arg1);
}

export function SetPortableMode(arg1) {
  return window['go']['main']['App']['SetPortableMode'](arg1);
}

export function SetSelectedVersion(arg1) {
  return window['go']['main']['App']['SetSelectedVersion'](arg1);
}

export function SetServerOnlineMode(arg1, arg2) {
  return window['go']['main']['App']['SetServerOnlineMode'](arg1, arg2);
}

export function SetShowExportLaunchCommand(arg1) {
  return window['go']['main']['App']['SetShowExportLaunchCommand'](arg1);
}

export function SetThemeColor(arg1) {
  return window['go']['main']['App']['SetThemeColor'](arg1);
}

export function SetVersionIsolation(arg1) {
  return window['go']['main']['App']['SetVersionIsolation'](arg1);
}

export function StartDownloadList() {
  return window['go']['main']['App']['StartDownloadList']();
}

export function StartMicrosoftLogin() {
  return window['go']['main']['App']['StartMicrosoftLogin']();
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ToggleMod(arg1, arg2) {
  return window['go']['main']['App']['ToggleMod'](arg1, arg2);
}

export function TranslateModName(arg1) {
  return window['go']['main']['App']['TranslateModName'](arg1);
}

export function UnlockGuest(arg1) {
  return window['go']['main']['App']['UnlockGuest'](arg1);
}

export function UserHasPassword(arg1) {
  return window['go']['main']['App']['UserHasPassword'](arg1);
}

export function WaitForServerReady() {
  return window['go']['main']['App']['WaitForServerReady']();
}
