// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddJavaToDownloadList(arg1:number):Promise<void>;

export function AddLoaderToDownloadList(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddModToDownloadList(arg1:string,arg2:string):Promise<void>;

export function AddModpackToDownloadList(arg1:string,arg2:string):Promise<void>;

export function AddToDownloadList(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddToDownloadListWithLoader(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function CancelDownloadList():Promise<void>;

export function CheckFirstRun():Promise<boolean>;

export function CheckLoaderInstalled(arg1:string,arg2:string):Promise<boolean>;

export function CreateExternalUser(arg1:string,arg2:main.ExternalAuthData):Promise<void>;

export function CreateGuestUser(arg1:string,arg2:string):Promise<void>;

export function CreateOfflineUser(arg1:string,arg2:string):Promise<void>;

export function CreatePremiumUser(arg1:string,arg2:main.MSAuthData):Promise<void>;

export function CreateServer(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:string):Promise<void>;

export function CreateUser(arg1:string,arg2:string):Promise<void>;

export function DeleteMod(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DownloadAuthlibInjector():Promise<string>;

export function DownloadVersion(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GenerateConnectionCode(arg1:string):Promise<Record<string, string>>;

export function GetAppDir():Promise<string>;

export function GetAuthlibInjectorPath():Promise<string>;

export function GetBackgroundImage():Promise<string>;

export function GetBackgroundImageDataURL():Promise<string>;

export function GetBingDailyImage():Promise<string>;

export function GetCachedBingImage():Promise<string>;

export function GetCurrentUser():Promise<main.UserInfo>;

export function GetDefaultModDir(arg1:string):Promise<string>;

export function GetDownloadList():Promise<Array<main.DownloadItem>>;

export function GetDownloadListCount():Promise<number>;

export function GetDownloadProgress():Promise<main.DownloadProgress>;

export function GetExternalAuthData(arg1:string):Promise<main.ExternalAuthData>;

export function GetFabricVersions(arg1:string):Promise<Array<main.LoaderInfo>>;

export function GetForgeVersions(arg1:string):Promise<Array<main.LoaderInfo>>;

export function GetGlobalConfig():Promise<main.GlobalConfig>;

export function GetInstalledVersions():Promise<Array<main.InstalledVersionInfo>>;

export function GetJavaDownloadList():Promise<Array<main.JavaDownloadInfo>>;

export function GetJavaInfo(arg1:string):Promise<main.JavaEntry>;

export function GetJavaRequirement(arg1:string):Promise<main.JavaVersionReq>;

export function GetLaunchCommand(arg1:string):Promise<string>;

export function GetMSAuthData(arg1:string):Promise<main.MSAuthData>;

export function GetMinecraftDir():Promise<string>;

export function GetModDependencies(arg1:string):Promise<Array<main.ModDependencyInfo>>;

export function GetModDetail(arg1:string):Promise<main.ModDetail>;

export function GetModList(arg1:string):Promise<Array<main.ModFileInfo>>;

export function GetModTranslationFileContent():Promise<string>;

export function GetModVersions(arg1:string,arg2:string,arg3:string):Promise<Array<main.ModVersion>>;

export function GetModpackVersions(arg1:string):Promise<Array<main.ModVersion>>;

export function GetModrinthCategories():Promise<Array<main.ModCategory>>;

export function GetNeoForgeVersions(arg1:string):Promise<Array<main.LoaderInfo>>;

export function GetOptiFineVersions(arg1:string):Promise<Array<main.LoaderInfo>>;

export function GetPortableJavaInfo():Promise<main.JavaEntry>;

export function GetPortableJavaPath():Promise<string>;

export function GetQGLDir():Promise<string>;

export function GetRecommendedJavaForVersion(arg1:string):Promise<number>;

export function GetSelectedVersion():Promise<string>;

export function GetServerDir():Promise<string>;

export function GetServerList():Promise<Array<main.ServerConfig>>;

export function GetServerLogs():Promise<Array<string>>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetShowExportLaunchCommand():Promise<boolean>;

export function GetThemeColor():Promise<string>;

export function GetTranslationCount():Promise<number>;

export function GetUserConfig(arg1:string):Promise<main.UserConfig>;

export function GetUserType(arg1:string):Promise<main.UserType>;

export function GetUsers():Promise<Array<main.UserInfo>>;

export function GetUsersDir():Promise<string>;

export function GetVersionManifest():Promise<Array<main.MCVersion>>;

export function GetYggdrasilServerInfo(arg1:string):Promise<main.YggdrasilServerInfo>;

export function ImportMod(arg1:string):Promise<void>;

export function InstallFabric(arg1:string,arg2:string):Promise<void>;

export function InstallForge(arg1:string,arg2:string):Promise<void>;

export function InstallNeoForge(arg1:string,arg2:string):Promise<void>;

export function InstallOptiFine(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IsGuestLocked():Promise<boolean>;

export function IsPortableMode():Promise<boolean>;

export function IsVersionIsolation():Promise<boolean>;

export function LaunchGame(arg1:string):Promise<void>;

export function LockGuest():Promise<void>;

export function LoginUser(arg1:string,arg2:string):Promise<void>;

export function LoginYggdrasil(arg1:string,arg2:string,arg3:string):Promise<main.ExternalAuthData>;

export function ParseConnectionCode(arg1:string):Promise<string>;

export function ReadLicenseFile():Promise<string>;

export function RefreshExternalToken(arg1:string):Promise<void>;

export function RefreshMicrosoftToken(arg1:string):Promise<void>;

export function RemoveFromDownloadList(arg1:string):Promise<void>;

export function ResolveModDependencies(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<main.ModDependencyResult>>;

export function SaveExternalAuthData(arg1:string,arg2:main.ExternalAuthData):Promise<void>;

export function SaveGlobalConfig(arg1:main.GlobalConfig):Promise<void>;

export function SaveMSAuthData(arg1:string,arg2:main.MSAuthData):Promise<void>;

export function SaveUserConfig(arg1:string,arg2:main.UserConfig):Promise<void>;

export function ScanVersions():Promise<Array<main.InstalledVersionInfo>>;

export function SearchJava():Promise<Array<main.JavaEntry>>;

export function SearchModpacks(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ModSearchResponse>;

export function SearchMods(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<main.ModSearchResponse>;

export function SearchModsByChineseName(arg1:string):Promise<Array<string>>;

export function SelectBackgroundImage():Promise<string>;

export function SelectJavaForVersion(arg1:string):Promise<main.JavaEntry>;

export function SelectModSaveDir():Promise<string>;

export function SendServerCommand(arg1:string):Promise<void>;

export function SetBackgroundImage(arg1:string):Promise<void>;

export function SetCurrentUser(arg1:string):Promise<void>;

export function SetPortableMode(arg1:boolean):Promise<void>;

export function SetSelectedVersion(arg1:string):Promise<void>;

export function SetServerOnlineMode(arg1:string,arg2:boolean):Promise<void>;

export function SetShowExportLaunchCommand(arg1:boolean):Promise<void>;

export function SetThemeColor(arg1:string):Promise<void>;

export function SetVersionIsolation(arg1:boolean):Promise<void>;

export function StartDownloadList():Promise<void>;

export function StartMicrosoftLogin():Promise<string>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer():Promise<void>;

export function ToggleMod(arg1:string,arg2:boolean):Promise<void>;

export function TranslateModName(arg1:string):Promise<string>;

export function UnlockGuest(arg1:string):Promise<void>;

export function UserHasPassword(arg1:string):Promise<boolean>;

export function WaitForServerReady():Promise<void>;
